### ISSUE TITLE
Edit Button Doesn't Do Anything But...

### ISSUE THREAD

**Issue by HonestAbe7** [WeAreFairphone/android_packages_apps_ClockWidget#21] opened 2022-05-29 19:28 UTC
Clicking the "Edit" option or button opens the system clock and alarm settings. Do I need the whole app to do this? Thanks

**Comment by Roboe** [comment] 2022-06-12 12:42
I don't know if I understood your question. Do you mean if you need the Fairphone Clock Widget to open your system clock and alarm settings? If so, the answer is no: the Edit button on the widget is just a convenience, you can open your system clock regularly through your Clock app, or similar.

**Comment by HonestAbe7** [comment] 2022-06-12 15:10
Well, the Edit button just opens my system clock. Not sure if the Edit button is supposed to edit the layout and date format, font, etc. for the widget or just open the system clock settings.

**Comment by Roboe** [comment] 2022-06-15 06:47
Oh, I understand now. Great appreciation. The expected behaviour is opening the Clock app in order to change or setup alarms. The widget appearance cannot be customized, it follows your system date and time settings, if I recall correctly.

You're right, the wording of the button label is not the best.

**Comment by HonestAbe7** [comment] 2022-06-21 01:05
No worries, I thought I was missing something. Would welcome a way to edit the appearance as described above in any future versions. 😊

**Comment by Roboe** [comment] 2022-08-13 09:28
To be clear: right now this project is on a hold state. The main objective, to make the original Fairphone Clock widget from Fairphone OS available to the public through the F-Droid store, was successfully fulfilled time ago.

However, if anybody is willing to add some feature like the one you bring here, that would be great. Since your original question was addressed and I honestly think further development is unlikely, I'll close this issue.

Even though, if you or other reader have the knowledge and time to do so, please step in! Comment here your intention to re-open the issue (or open a new one, at your will) so we can be in touch!

Thanks for your time and input, @HonestAbe7!

**Closed as completed by Roboe** 2022-08-13 09:28 UTC
Labels: question
